'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pemesanan_Tiket_Bioskop.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tunjungan Plaza 1, Lantai 5, Jl. Basuki Rahmat No. 8-12, Surabaya.
        '''</summary>
        Friend ReadOnly Property Alamat1() As String
            Get
                Return ResourceManager.GetString("Alamat1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tunjungan Plaza 3, Lantai 5, Jl. Basuki Rahmat No. 8-12, Surabaya.
        '''</summary>
        Friend ReadOnly Property Alamat2() As String
            Get
                Return ResourceManager.GetString("Alamat2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tunjungan Plaza 5, Lantai 10, Jl. Basuki Rahmat No. 8-12, Surabaya.
        '''</summary>
        Friend ReadOnly Property Alamat3() As String
            Get
                Return ResourceManager.GetString("Alamat3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keanu Reeves, Wiona Ryder, DJ Dallenbach, Ted Dubost, D. Rosh, Wright, Greg Lucey, Donna Lynn Jones.
        '''</summary>
        Friend ReadOnly Property Casts1() As String
            Get
                Return ResourceManager.GetString("Casts1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liam Neeson, Kate Walsh, Jai Courtney, Jeffrey Donovan, Anthony Ramos, Robert Patrick, Birol Tarkan Yildiz, Tazzie, Adam Teper.
        '''</summary>
        Friend ReadOnly Property Casts2() As String
            Get
                Return ResourceManager.GetString("Casts2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jin Zhang, Anderson Silva, Kevin Cheng, Annie Liu, Stephy Tang, Juju Chan, Endy Chow, Suet Lam, Richard Ng.
        '''</summary>
        Friend ReadOnly Property Casts3() As String
            Get
                Return ResourceManager.GetString("Casts3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comedy, Drama, Romance.
        '''</summary>
        Friend ReadOnly Property Genre1() As String
            Get
                Return ResourceManager.GetString("Genre1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action, Crime, Drama.
        '''</summary>
        Friend ReadOnly Property Genre2() As String
            Get
                Return ResourceManager.GetString("Genre2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action, Adventure, Crime.
        '''</summary>
        Friend ReadOnly Property Genre3() As String
            Get
                Return ResourceManager.GetString("Genre3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Destination Wedding.
        '''</summary>
        Friend ReadOnly Property Judul1() As String
            Get
                Return ResourceManager.GetString("Judul1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Honest Theif.
        '''</summary>
        Friend ReadOnly Property Judul2() As String
            Get
                Return ResourceManager.GetString("Judul2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invincible Dragon.
        '''</summary>
        Friend ReadOnly Property Judul3() As String
            Get
                Return ResourceManager.GetString("Judul3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Victor Levin.
        '''</summary>
        Friend ReadOnly Property Penulis1() As String
            Get
                Return ResourceManager.GetString("Penulis1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steve Allrich, Mark Williams.
        '''</summary>
        Friend ReadOnly Property Penulis2() As String
            Get
                Return ResourceManager.GetString("Penulis2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fruit Chan, Kee-To Lam.
        '''</summary>
        Friend ReadOnly Property Penulis3() As String
            Get
                Return ResourceManager.GetString("Penulis3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Poster1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Poster1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Poster2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Poster2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Poster3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Poster3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regatta.
        '''</summary>
        Friend ReadOnly Property Produksi1() As String
            Get
                Return ResourceManager.GetString("Produksi1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solution Entertainment Group.
        '''</summary>
        Friend ReadOnly Property Produksi2() As String
            Get
                Return ResourceManager.GetString("Produksi2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pegasus Motion Pictures.
        '''</summary>
        Friend ReadOnly Property Produksi3() As String
            Get
                Return ResourceManager.GetString("Produksi3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elizabeth Dell, Robert Jones.
        '''</summary>
        Friend ReadOnly Property Produsen1() As String
            Get
                Return ResourceManager.GetString("Produsen1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Craig Chapman, Charlie Dorfman, Myles Nestel, Mark Williams.
        '''</summary>
        Friend ReadOnly Property Produsen2() As String
            Get
                Return ResourceManager.GetString("Produsen2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fruit Chan, Amy Chin, John Chong, Raymond Pak-Ming Wong, Dong Yu.
        '''</summary>
        Friend ReadOnly Property Produsen3() As String
            Get
                Return ResourceManager.GetString("Produsen3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kisah dua tamu pernikahan yang punya cerita menyedihkan dan tidak menyenangkan. Lindsay (Wiona Ryder) dan Frank (Keanu Reeves) sepakat untuk memiliki latar belakang kasih sayang walaupun sebenarnya mereka tidak bersama..
        '''</summary>
        Friend ReadOnly Property Sinopsis1() As String
            Get
                Return ResourceManager.GetString("Sinopsis1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tom (Liam Neeson) adalah seorang perampok bank yang ingin merubah hidupnya. Ia berniat menyerahkan diri kepada FBI dan menjalani hidup dengan jujur. Namun niat tulus Tom ternyata dimanfaatkan oleh dua agen yang ingin menguasai hasil rampokannya. Kini Tom berusaha membersihkan namanya, pasca ia dituduh melakukan pembunuhan..
        '''</summary>
        Friend ReadOnly Property Sinopsis2() As String
            Get
                Return ResourceManager.GetString("Sinopsis2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seorang agen yang sedang menyamar, membantu kepolisian Hong Kong untuk memecahkan kasus pembunuhan misterius. Namun sifatnya yang keras membawanya ke dalam masalah yang tidak ada habisnya..
        '''</summary>
        Friend ReadOnly Property Sinopsis3() As String
            Get
                Return ResourceManager.GetString("Sinopsis3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Victor Levin.
        '''</summary>
        Friend ReadOnly Property Sutradara1() As String
            Get
                Return ResourceManager.GetString("Sutradara1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mark Williams.
        '''</summary>
        Friend ReadOnly Property Sutradara2() As String
            Get
                Return ResourceManager.GetString("Sutradara2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fruit Chan.
        '''</summary>
        Friend ReadOnly Property Sutradara3() As String
            Get
                Return ResourceManager.GetString("Sutradara3", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
